# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp3playerGUI-pyqt5-main_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 257)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(10, 170, 120, 34))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.OpenButton.setFont(font)
        self.OpenButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenButton.setMouseTracking(True)
        self.OpenButton.setAutoDefault(False)
        self.OpenButton.setObjectName("OpenButton")
        self.PlayButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayButton.setGeometry(QtCore.QRect(160, 170, 50, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayButton.sizePolicy().hasHeightForWidth())
        self.PlayButton.setSizePolicy(sizePolicy)
        self.PlayButton.setObjectName("PlayButton")
        self.BackwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackwardButton.setGeometry(QtCore.QRect(120, 170, 50, 34))
        self.BackwardButton.setObjectName("BackwardButton")
        self.ForwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.ForwardButton.setGeometry(QtCore.QRect(200, 170, 50, 34))
        self.ForwardButton.setObjectName("ForwardButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(240, 170, 50, 34))
        self.StopButton.setObjectName("StopButton")
        self.Timepassed = QtWidgets.QLabel(self.centralwidget)
        self.Timepassed.setGeometry(QtCore.QRect(20, 130, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Timepassed.setFont(font)
        self.Timepassed.setObjectName("Timepassed")
        self.Timeleft = QtWidgets.QLabel(self.centralwidget)
        self.Timeleft.setGeometry(QtCore.QRect(270, 130, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Timeleft.setFont(font)
        self.Timeleft.setObjectName("Timeleft")
        self.Volumedial = QtWidgets.QDial(self.centralwidget)
        self.Volumedial.setGeometry(QtCore.QRect(350, 140, 51, 51))
        self.Volumedial.setWrapping(False)
        self.Volumedial.setNotchTarget(2.7)
        self.Volumedial.setNotchesVisible(True)
        self.Volumedial.setObjectName("Volumedial")
        self.Timeline = QtWidgets.QSlider(self.centralwidget)
        self.Timeline.setGeometry(QtCore.QRect(19, 150, 321, 22))
        self.Timeline.setMaximum(99)
        self.Timeline.setOrientation(QtCore.Qt.Horizontal)
        self.Timeline.setObjectName("Timeline")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 321, 121))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
#        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(13)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setHighlightSections(False)

        self.addToQueue = QtWidgets.QPushButton(self.centralwidget)
        self.addToQueue.setGeometry(QtCore.QRect(340, 3, 50, 34))
        self.addToQueue.setObjectName("addToQueue")
        self.muteButton = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(300, 170, 50, 34))
        self.muteButton.setObjectName("muteButton")
        self.PlayingIcon = QtWidgets.QLabel(self.centralwidget)
        self.PlayingIcon.setGeometry(QtCore.QRect(390, 3, 30, 30))
        self.PlayingIcon.setObjectName("PlayingIcon")
        self.shuffleButton = QtWidgets.QPushButton(self.centralwidget)
        self.shuffleButton.setGeometry(QtCore.QRect(340, 105, 50, 34))
        self.shuffleButton.setObjectName("shuffleButton")
        self.repeatButton = QtWidgets.QPushButton(self.centralwidget)
        self.repeatButton.setGeometry(QtCore.QRect(340, 81, 50, 34))
        self.repeatButton.setObjectName("repeatButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Peders Magnificient MP3 Player"))
        self.OpenButton.setText(_translate("MainWindow", "Select song"))
        self.PlayButton.setText(_translate("MainWindow", "Play"))
        self.BackwardButton.setText(_translate("MainWindow", "Backward"))
        self.ForwardButton.setText(_translate("MainWindow", "Forward"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.Timepassed.setText(_translate("MainWindow", "Timepassed"))
        self.Timeleft.setText(_translate("MainWindow", "Timeleft"))
        self.addToQueue.setText(_translate("MainWindow", "AddtoQue"))
        self.muteButton.setText(_translate("MainWindow", "muteButton"))
        self.PlayingIcon.setText(_translate("MainWindow", "PlayingIcon"))
        self.shuffleButton.setText(_translate("MainWindow", "shuffle"))
        self.repeatButton.setText(_translate("MainWindow", "PushButton"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
